#ifndef _REFEREE_MAIN_CONFIG_H_
#define _REFEREE_MAIN_CONFIG_H_

#define REFEREE_MAIN_ARMOR_COUNT              4U
#define REFEREE_MAIN_ARMOR_RX_BUFFER_SIZE     64U
#define REFEREE_MAIN_ARMOR_PACKET_SIZE        8U
#define REFEREE_MAIN_ARMOR_EVENT_QUEUE_LENGTH 16U
#define REFEREE_MAIN_ARMOR_EVENT_WORDS        4U
#define REFEREE_MAIN_FRAME_CAPACITY           127U

#define REFEREE_MAIN_BUTTON_ENABLE            1U
#define REFEREE_MAIN_KEY1_ENABLE              1U
#define REFEREE_MAIN_KEY2_ENABLE              1U
#define REFEREE_MAIN_KEY_ACTIVE_LEVEL         0U
#define REFEREE_MAIN_KEY_DEBOUNCE_MS          20U
#define REFEREE_MAIN_KEY_POLL_PERIOD_MS       10U

#define REFEREE_MAIN_WATCHDOG_ENABLE          1U
#define REFEREE_MAIN_WATCHDOG_PERIOD_MS       100U
#define REFEREE_MAIN_WATCHDOG_STACK_SIZE      512U

#define REFEREE_MAIN_LED_ENABLE               1U
#define REFEREE_MAIN_LED_ACTIVE_LEVEL         1U
#define REFEREE_MAIN_LED_INACTIVE_LEVEL       0U

#define REFEREE_MAIN_TEAM_RED                 0U
#define REFEREE_MAIN_TEAM_BLUE                1U
#define REFEREE_MAIN_INITIAL_TEAM             REFEREE_MAIN_TEAM_RED
#define REFEREE_MAIN_ROBOT_ID_RED             3U
#define REFEREE_MAIN_ROBOT_ID_BLUE            103U

#define REFEREE_MAIN_ROBOT_LEVEL              1U
#define REFEREE_MAIN_MAX_HP                   400U
#define REFEREE_MAIN_HURT_DAMAGE              10U
#define REFEREE_MAIN_CHASSIS_POWER_LIMIT      45U

#define REFEREE_MAIN_TX_PERIOD_MS             100U
#define REFEREE_MAIN_HP_PERIOD_MS             333U
#define REFEREE_MAIN_GAME_PERIOD_MS           1000U
#define REFEREE_MAIN_ARMOR_OFFLINE_TIMEOUT_MS 500U
#define REFEREE_MAIN_HIT_DEDUP_MS             1000U

#define REFEREE_MAIN_ARMOR_EVENT_HEARTBEAT    0U
#define REFEREE_MAIN_ARMOR_EVENT_HIT_DX       1U
#define REFEREE_MAIN_ARMOR_EVENT_HIT_ADC      2U
#define REFEREE_MAIN_ARMOR_EVENT_HIT_BOTH     3U

#define REFEREE_MAIN_ARMOR_CONFIG_CMD         0xC1U
#define REFEREE_MAIN_ARMOR_CONFIG_SIZE        8U
#define REFEREE_MAIN_ARMOR_CONFIG_PERIOD_MS  100U

#endif
