#ifndef _REFEREE_MAIN_CONFIG_H_
#define _REFEREE_MAIN_CONFIG_H_

#define REFEREE_MAIN_ARMOR_COUNT              4U
#define REFEREE_MAIN_ARMOR_RX_BUFFER_SIZE     64U
#define REFEREE_MAIN_ARMOR_PACKET_SIZE        8U
#define REFEREE_MAIN_ARMOR_EVENT_QUEUE_LENGTH 16U
#define REFEREE_MAIN_ARMOR_EVENT_WORDS        4U
#define REFEREE_MAIN_FRAME_CAPACITY           127U

#define REFEREE_MAIN_ROBOT_ID                 3U
#define REFEREE_MAIN_ROBOT_LEVEL              1U
#define REFEREE_MAIN_MAX_HP                   400U
#define REFEREE_MAIN_HURT_DAMAGE              10U
#define REFEREE_MAIN_CHASSIS_POWER_LIMIT      45U

#define REFEREE_MAIN_TX_PERIOD_MS             100U
#define REFEREE_MAIN_HP_PERIOD_MS             333U
#define REFEREE_MAIN_GAME_PERIOD_MS           1000U
#define REFEREE_MAIN_ARMOR_OFFLINE_TIMEOUT_MS 500U
#define REFEREE_MAIN_HIT_DEDUP_MS             1000U

#define REFEREE_MAIN_ARMOR_EVENT_HEARTBEAT    0U
#define REFEREE_MAIN_ARMOR_EVENT_HIT_DX       1U
#define REFEREE_MAIN_ARMOR_EVENT_HIT_ADC      2U
#define REFEREE_MAIN_ARMOR_EVENT_HIT_BOTH     3U

#endif
