#ifndef ARMOR_CONFIG_H
#define ARMOR_CONFIG_H

#define ARMOR_ID                  0U
#define ARMOR_MAX_ID              3U
#define ARMOR_TEAM_RED            0U
#define ARMOR_TEAM_BLUE           1U
#define ARMOR_DX_ACTIVE_HIGH      1U
#define ARMOR_HEARTBEAT_PERIOD_MS 50U
#define ARMOR_BASELINE_TIME_MS    500U
#define ARMOR_BASELINE_SAMPLES    64U
#define ARMOR_HIT_COOLDOWN_MS     50U
#define ARMOR_HIT_LED_PHASE_MS    100U
#define ARMOR_BIG_HIT_ADC_THRESHOLD 4095U
#define ARMOR_PACKET_SIZE         8U
#define ARMOR_STATUS_ARMOR_ID_MASK 0x7FU
#define ARMOR_STATUS_RESET_ACK    0x80U
#define ARMOR_TX_QUEUE_CAPACITY   16U
#define ARMOR_RX_QUEUE_CAPACITY   64U
#define ARMOR_LINK_FRAME_SIZE     8U
#define ARMOR_LINK_CMD_CONFIG     0xC1U
#define ARMOR_LINK_MODE_ENABLE    0x01U
#define ARMOR_LINK_MODE_RESET_COUNTERS 0x02U
#define ARMOR_LINK_MODE_ADC_DEBUG 0x04U
#define ARMOR_ADC_HISTORY_COUNT   4U
#define ARMOR_ADC_DEBUG_CMD       0xD1U
#define ARMOR_ADC_DEBUG_FRAME_SIZE 11U
#define ARMOR_LINK_ONLINE_TIMEOUT_MS 500U
#define ARMOR_LINK_FLASH_HALF_PERIOD_MS 100U
#define ARMOR_KEY_DEBOUNCE_MS     20U

#endif
