#ifndef ARMOR_CONFIG_H
#define ARMOR_CONFIG_H

#define ARMOR_ID                  0U
#define ARMOR_DX_ACTIVE_HIGH      1U
#define ARMOR_HEARTBEAT_PERIOD_MS 50U
#define ARMOR_BASELINE_TIME_MS    500U
#define ARMOR_BASELINE_SAMPLES    64U
#define ARMOR_AX_THRESHOLD        250U
#define ARMOR_HIT_COOLDOWN_MS     100U
#define ARMOR_HIT_LED_HOLD_MS     500U
#define ARMOR_HIT_REPEAT_COUNT    3U
#define ARMOR_HIT_REPEAT_GAP_MS   5U
#define ARMOR_PACKET_SIZE         8U
#define ARMOR_DEBUG_SAMPLE_COUNT  256U

#endif
